import type { CardReference, CharacterReference, RoleReference, RoleDistributionEntry } from "./types.ts";

export const suitSymbols: Record<string, string> = {
  Spades: "\u2660",
  Hearts: "\u2665",
  Diamonds: "\u2666",
  Clubs: "\u2663",
};

export const suitColors: Record<string, string> = {
  Spades: "#a0a0b0",
  Hearts: "#e04040",
  Diamonds: "#e04040",
  Clubs: "#a0a0b0",
};

export const cardTypeLabels: Record<string, string> = {
  Bang: "Бэнг!",
  Missed: "Мимо!",
  Beer: "Пиво",
  Gatling: "Гатлинг",
  Stagecoach: "Дилижанс",
  CatBalou: "Красотка",
  Indians: "Индейцы!",
  Duel: "Дуэль",
  Panic: "Паника!",
  Saloon: "Салун",
  WellsFargo: "Уэллс Фарго",
  GeneralStore: "Магазин",
  Barrel: "Бочка",
  Mustang: "Мустанг",
  Scope: "Прицел",
  Volcanic: "Вулканик",
  Schofield: "Скофилд",
  Remington: "Ремингтон",
  RevCarabine: "Карабин",
  Winchester: "Винчестер",
  Jail: "Тюрьма",
  Dynamite: "Динамит",
  // Dodge City
  Punch: "Удар",
  Springfield: "Спрингфилд",
  Dodge: "Уворот",
  Whisky: "Виски",
  Tequila: "Текила",
  RagTime: "Рэгтайм",
  Brawl: "Потасовка",
  CanCan: "Канкан",
  Conestoga: "Фургон",
  Derringer: "Дерринджер",
  Pepperbox: "Пепербокс",
  Howitzer: "Гаубица",
  BuffaloRifle: "Буффало",
  Canteen: "Фляга",
  Bible: "Библия",
  IronPlate: "Железный щит",
  Sombrero: "Сомбреро",
  TenGallonHat: "Шляпа",
  Hideout: "Укрытие",
  Silver: "Серебро",
};

export const cardCategoryLabels: Record<string, string> = {
  Brown: "Коричневая",
  Blue: "Синяя",
  Weapon: "Оружие",
  Green: "Зелёная",
};

export const cardsReference: CardReference[] = [
  { name: "Бэнг!", type: "Bang", description: "Нанесите 1 урон (2, если вы Слэб Убийца).", imagePath: "/assets/cards/bang.webp" },
  { name: "Мимо!", type: "Missed", description: "Сыграйте в ответ на выстрел, чтобы отменить урон.", imagePath: "/assets/cards/missed.webp" },
  { name: "Пиво", type: "Beer", description: "Восстановите 1 ОЗ. Недоступно, когда осталось 2 игрока.", imagePath: "/assets/cards/beer.webp" },
  { name: "Гатлинг", type: "Gatling", description: "Каждый другой игрок должен сыграть Мимо! или получить 1 урон.", imagePath: "/assets/cards/gatling.webp" },
  { name: "Дилижанс", type: "Stagecoach", description: "Доберите 2 карты.", imagePath: "/assets/cards/stagecoach.webp" },
  { name: "Красотка", type: "CatBalou", description: "Заставьте цель сбросить карту (рука или снаряжение).", imagePath: "/assets/cards/cat_balou.webp" },
  { name: "Индейцы!", type: "Indians", description: "Каждый другой игрок должен сбросить Бэнг! или получить 1 урон.", imagePath: "/assets/cards/indians.webp" },
  { name: "Дуэль", type: "Duel", description: "Вызовите игрока на дуэль — по очереди сбрасывайте Бэнг!.", imagePath: "/assets/cards/duel.webp" },
  { name: "Паника!", type: "Panic", description: "Украдите карту у игрока на дистанции 1.", imagePath: "/assets/cards/panic.webp" },
  { name: "Салун", type: "Saloon", description: "Все живые игроки лечатся на 1 ОЗ.", imagePath: "/assets/cards/saloon.webp" },
  { name: "Уэллс Фарго", type: "WellsFargo", description: "Доберите 3 карты.", imagePath: "/assets/cards/wells_fargo.webp" },
  { name: "Магазин", type: "GeneralStore", description: "Откройте карты по числу живых игроков. Каждый выбирает одну.", imagePath: "/assets/cards/general_store.webp" },
  { name: "Бочка", type: "Barrel", description: "При выстреле, «проверка» — если червы, выстрел избегается.", imagePath: "/assets/cards/barrel.webp" },
  { name: "Мустанг", type: "Mustang", description: "Другие видят вас на дистанции +1.", imagePath: "/assets/cards/mustang.webp" },
  { name: "Прицел", type: "Scope", description: "Вы видите других на дистанции -1.", imagePath: "/assets/cards/scope.webp" },
  { name: "Вулканик", type: "Volcanic", description: "Оружие (дальность 1). Можно играть Бэнг! без ограничения за ход.", imagePath: "/assets/cards/volcanic.webp" },
  { name: "Скофилд", type: "Schofield", description: "Оружие (дальность 2).", imagePath: "/assets/cards/schofield.webp" },
  { name: "Ремингтон", type: "Remington", description: "Оружие (дальность 3).", imagePath: "/assets/cards/remington.webp" },
  { name: "Карабин", type: "RevCarabine", description: "Оружие (дальность 4).", imagePath: "/assets/cards/rev_carabine.webp" },
  { name: "Винчестер", type: "Winchester", description: "Оружие (дальность 5).", imagePath: "/assets/cards/winchester.webp" },
  // Dodge City
  { name: "Удар", type: "Punch", description: "Нанесите 1 урон цели на дистанции 1. Не считается как Бэнг!.", imagePath: "/assets/cards/punch.svg" },
  { name: "Спрингфилд", type: "Springfield", description: "Сбросьте 1 карту — цель на любой дистанции получает 1 урон.", imagePath: "/assets/cards/springfield.svg" },
  { name: "Уворот", type: "Dodge", description: "Как Мимо!, но после использования доберите 1 карту.", imagePath: "/assets/cards/dodge.svg" },
  { name: "Виски", type: "Whisky", description: "Сбросьте 1 карту — восстановите 2 ОЗ.", imagePath: "/assets/cards/whisky.svg" },
  { name: "Текила", type: "Tequila", description: "Сбросьте 1 карту — любой игрок восстанавливает 1 ОЗ.", imagePath: "/assets/cards/tequila.svg" },
  { name: "Рэгтайм", type: "RagTime", description: "Сбросьте 1 карту — украдите карту у любого игрока.", imagePath: "/assets/cards/rag_time.svg" },
  { name: "Потасовка", type: "Brawl", description: "Сбросьте 1 карту — каждый другой игрок сбрасывает 1 карту.", imagePath: "/assets/cards/brawl.svg" },
  { name: "Канкан", type: "CanCan", description: "Заставьте любого игрока сбросить карту (любая дистанция).", imagePath: "/assets/cards/can_can.svg" },
  { name: "Фургон", type: "Conestoga", description: "Украдите карту у любого игрока (любая дистанция).", imagePath: "/assets/cards/conestoga.svg" },
  { name: "Дерринджер", type: "Derringer", description: "Активируйте: Бэнг! на дистанции 1 + доберите 1 карту.", imagePath: "/assets/cards/derringer.svg" },
  { name: "Пепербокс", type: "Pepperbox", description: "Активируйте: Бэнг! на любой дистанции.", imagePath: "/assets/cards/pepperbox.svg" },
  { name: "Гаубица", type: "Howitzer", description: "Активируйте: как Гатлинг (все получают 1 урон или Мимо!).", imagePath: "/assets/cards/howitzer.svg" },
  { name: "Буффало", type: "BuffaloRifle", description: "Активируйте: Бэнг! на любой дистанции.", imagePath: "/assets/cards/buffalo_rifle.svg" },
  { name: "Фляга", type: "Canteen", description: "Активируйте: восстановите 1 ОЗ.", imagePath: "/assets/cards/canteen.svg" },
  { name: "Библия", type: "Bible", description: "Реакция: уклонитесь от Бэнг! (из снаряжения).", imagePath: "/assets/cards/bible.svg" },
  { name: "Железный щит", type: "IronPlate", description: "Реакция: уклонитесь от Бэнг! (из снаряжения).", imagePath: "/assets/cards/iron_plate.svg" },
  { name: "Сомбреро", type: "Sombrero", description: "Реакция: уклонитесь от Бэнг! (из снаряжения).", imagePath: "/assets/cards/sombrero.svg" },
  { name: "Шляпа", type: "TenGallonHat", description: "Реакция: уклонитесь от Бэнг! (из снаряжения).", imagePath: "/assets/cards/ten_gallon_hat.svg" },
  { name: "Укрытие", type: "Hideout", description: "Другие видят вас на дистанции +1.", imagePath: "/assets/cards/hideout.svg" },
  { name: "Серебро", type: "Silver", description: "Вы видите других на дистанции -1.", imagePath: "/assets/cards/silver.svg" },
];

export const charactersReference: CharacterReference[] = [
  { name: "Счастливчик Дьюк", description: "При «проверке» откройте 2 карты и выберите лучший результат.", portraitPath: "/assets/characters/lucky_duke.webp" },
  { name: "Слэб Убийца", description: "Ваши Бэнг! наносят 2 урона.", portraitPath: "/assets/characters/slab_the_killer.webp" },
  { name: "Эль Гринго", description: "При получении урона возьмите карту из руки атакующего.", portraitPath: "/assets/characters/el_gringo.webp" },
  { name: "Сьюзи Лафайет", description: "Когда рука становится пустой, возьмите 1 карту.", portraitPath: "/assets/characters/suzy_lafayette.webp" },
  { name: "Роуз Дулан", description: "Встроенный Прицел: вы видите других на дистанции -1.", portraitPath: "/assets/characters/rose_doolan.webp" },
  { name: "Джесси Джонс", description: "Первую карту берите из руки выбранного игрока.", portraitPath: "/assets/characters/jesse_jones.webp" },
  { name: "Барт Кэссиди", description: "Каждый раз при получении урона берите 1 карту из колоды.", portraitPath: "/assets/characters/bart_cassidy.webp" },
  { name: "Пол Регрет", description: "Встроенный Мустанг: другие видят вас на дистанции +1.", portraitPath: "/assets/characters/paul_regret.webp" },
  { name: "Каламити Джанет", description: "Используйте Бэнг! как Мимо! и Мимо! как Бэнг!.", portraitPath: "/assets/characters/calamity_janet.webp" },
  { name: "Кит Карлсон", description: "Посмотрите 3 верхние карты, оставьте 2, 1 верните.", portraitPath: "/assets/characters/kit_carlson.webp" },
  { name: "Уилли Кид", description: "Можно играть Бэнг! без ограничения за ход.", portraitPath: "/assets/characters/willy_the_kid.webp" },
  { name: "Сид Кетчум", description: "Сбросьте 2 карты, чтобы восстановить 1 ОЗ (в свой ход).", portraitPath: "/assets/characters/sid_ketchum.webp" },
  { name: "Стервятник Сэм", description: "Когда игрок устранён, возьмите все его карты.", portraitPath: "/assets/characters/vulture_sam.webp" },
  { name: "Педро Рамирес", description: "Первую карту берите из сброса.", portraitPath: "/assets/characters/pedro_ramirez.webp" },
  // Dodge City
  { name: "Апач Кид", description: "Бубновые карты других игроков не действуют на вас.", portraitPath: "/assets/characters/apache_kid.svg" },
  { name: "Белль Стар", description: "Во время вашего хода снаряжение других игроков не действует.", portraitPath: "/assets/characters/belle_star.svg" },
  { name: "Билл Ноуфейс", description: "Добирайте 1 + количество ранений карт в начале хода.", portraitPath: "/assets/characters/bill_noface.svg" },
  { name: "Чак Венгам", description: "Потеряйте 1 ОЗ — доберите 2 карты (в свой ход).", portraitPath: "/assets/characters/chuck_wengam.svg" },
  { name: "Док Холидэй", description: "Сбросьте 2 карты + цель — выстрел (1 раз/ход).", portraitPath: "/assets/characters/doc_holyday.svg" },
  { name: "Елена Фуэнте", description: "Любая карта из руки может быть использована как Мимо!.", portraitPath: "/assets/characters/elena_fuente.svg" },
  { name: "Грег Диггер", description: "Когда другой игрок устранён, восстановите 2 ОЗ.", portraitPath: "/assets/characters/greg_digger.svg" },
  { name: "Херб Хантер", description: "Когда другой игрок устранён, доберите 2 карты.", portraitPath: "/assets/characters/herb_hunter.svg" },
  { name: "Хосе Дельгадо", description: "Сбросьте синюю карту — доберите 2 (2 раза/ход).", portraitPath: "/assets/characters/jose_delgado.svg" },
  { name: "Молли Старк", description: "Когда вы играете карту вне своего хода, доберите 1 карту.", portraitPath: "/assets/characters/molly_stark.svg" },
  { name: "Пат Бреннан", description: "Вместо добора из колоды, возьмите 1 снаряжение другого игрока.", portraitPath: "/assets/characters/pat_brennan.svg" },
  { name: "Пикси Пит", description: "Добирайте 3 карты вместо 2.", portraitPath: "/assets/characters/pixie_pete.svg" },
  { name: "Шон Мэллори", description: "Нет лимита руки в конце хода.", portraitPath: "/assets/characters/sean_mallory.svg" },
  { name: "Текила Джо", description: "Пиво восстанавливает 2 ОЗ вместо 1.", portraitPath: "/assets/characters/tequila_joe.svg" },
  { name: "Вера Кастер", description: "В начале хода выберите персонажа для копирования.", portraitPath: "/assets/characters/vera_custer.svg" },
];

export const rolesReference: RoleReference[] = [
  { name: "Шериф", color: "#f3b169", description: "Цель — устранить всех Бандитов и Ренегата. Роль открыта, +1 ОЗ." },
  { name: "Помощник", color: "#6bc46b", description: "Защищает Шерифа. Побеждает вместе с ним." },
  { name: "Бандит", color: "#e04040", description: "Цель — устранить Шерифа." },
  { name: "Ренегат", color: "#7a8fe0", description: "Цель — остаться последним. Должен убить всех, включая Шерифа." },
];

export const roleDistribution: RoleDistributionEntry[] = [
  { players: 2, roles: "1 Шериф, 1 Бандит" },
  { players: 3, roles: "1 Шериф, 1 Бандит, 1 Ренегат" },
  { players: 4, roles: "1 Шериф, 2 Бандита, 1 Ренегат" },
  { players: 5, roles: "1 Шериф, 1 Помощник, 2 Бандита, 1 Ренегат" },
  { players: 6, roles: "1 Шериф, 1 Помощник, 3 Бандита, 1 Ренегат" },
];
