function getEl<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Element #${id} not found`);
  return el as T;
}

export const joinPanel = getEl<HTMLElement>("joinPanel");
export const gamePanel = getEl<HTMLElement>("gamePanel");
export const connectionStatus = getEl<HTMLElement>("connectionStatus");
export const joinButton = getEl<HTMLButtonElement>("joinButton");
export const playerNameInput = getEl<HTMLInputElement>("playerName");
export const startButton = getEl<HTMLButtonElement>("startButton");
export const endTurnButton = getEl<HTMLButtonElement>("endTurnButton");
export const abilityButton = getEl<HTMLButtonElement>("abilityButton");
export const playersContainer = getEl<HTMLElement>("players");
export const handCards = getEl<HTMLElement>("handCards");
export const handHint = getEl<HTMLElement>("handHint");
export const eventLog = getEl<HTMLElement>("eventLog");
export const chatLog = getEl<HTMLElement>("chatLog");
export const newGameButton = getEl<HTMLButtonElement>("newGameButton");
export const turnInfo = getEl<HTMLElement>("turnInfo");
export const chatInput = getEl<HTMLInputElement>("chatInput");
export const chatButton = getEl<HTMLButtonElement>("chatButton");
export const targetOverlay = getEl<HTMLElement>("targetOverlay");
export const targetList = getEl<HTMLElement>("targetList");
export const targetPrompt = getEl<HTMLElement>("targetPrompt");
export const cancelTarget = getEl<HTMLButtonElement>("cancelTarget");
export const cardLibrary = getEl<HTMLElement>("cardLibrary");
export const characterLibrary = getEl<HTMLElement>("characterLibrary");
export const responseOverlay = getEl<HTMLElement>("responseOverlay");
export const responseTitle = getEl<HTMLElement>("responseTitle");
export const responsePrompt = getEl<HTMLElement>("responsePrompt");
export const responseCards = getEl<HTMLElement>("responseCards");
export const responsePass = getEl<HTMLButtonElement>("responsePass");
export const abilityOverlay = getEl<HTMLElement>("abilityOverlay");
export const abilityCards = getEl<HTMLElement>("abilityCards");
export const abilityConfirm = getEl<HTMLButtonElement>("abilityConfirm");
export const cancelAbility = getEl<HTMLButtonElement>("cancelAbility");
export const lobbyPanel = getEl<HTMLElement>("lobbyPanel");
export const createRoomButton = getEl<HTMLButtonElement>("createRoomButton");
export const roomCodeInput = getEl<HTMLInputElement>("roomCodeInput");
export const joinRoomButton = getEl<HTMLButtonElement>("joinRoomButton");
export const roomListContainer = getEl<HTMLElement>("roomList");
export const leaveButton = getEl<HTMLButtonElement>("leaveButton");
export const renameButton = getEl<HTMLButtonElement>("renameButton");
export const spectatorBanner = getEl<HTMLElement>("spectatorBanner");
export const roomCodeBadge = getEl<HTMLElement>("roomCodeBadge");
export const roleLibrary = getEl<HTMLElement>("roleLibrary");
export const settingsPanel = getEl<HTMLElement>("settingsPanel");
export const settDodgeCity = getEl<HTMLInputElement>("settDodgeCity");
export const settHighNoon = getEl<HTMLInputElement>("settHighNoon");
export const settFistful = getEl<HTMLInputElement>("settFistful");
export const eventBanner = getEl<HTMLElement>("eventBanner");
